print("Tugas Python")
print()
nama=input("Masukkan Nama Anda:")
panggilan=input("Masukkan Panggilan:")
nim=input("Masukkan NIM:")
tanggallahir=input("Masukkan Tanggal Lahir:")
tempatlahir=input("Masukkan Tempat Lahir:")
telepon=input("Masukkan Telepon:")
alamat=input("Masukkan Alamat:")
umur=input("Masukkan Umur Anda:")
print()
print("Assalamu'alaikum")
print()
print("Let me introduce my self, my name is",nama,"but you can call me",panggilan,"My NIM is",nim,"I was born in",tempatlahir,"and I am",umur,
      "years old. I am very gald if you want to invite my house in",alamat,". So, don't forget to call me before with the number",telepon,)
print()
print("Thank you.")
